url: "https://maxlgross414.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Max L. Gross" # the name of your site, e.g. ACME Corp.
description: "Joint Honours Math/CS @ <a href="https://www.mcgill.ca" target="_blank">McGill University</a>
