menu:
- {name: 'cv', url: '../assets/ResumeMax.pdf'}
- {name: 'crosswords', url: '/crosswords'}
- {name: 'papers', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/maxlgross414'}
- {icon: 'twitter', link: 'https://x.com/maximumgross'}
- {icon: 'instagram', link: 'https://instagram.com/maximumgross'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/maxlgross'}

contacts:
- {name: 'Max Liam Gross', title: 'Student', department: 'Computer Science', institution: 'McGill University', institution_address: '3480 Rue University', phone: '+ 1 (416) 277-6508', email: 'max.gross HELLOROBOT mail.mcgill.ca', office: '225 McConnell Hall', image: 'assets/img/mcgill-outside-bw.jpg'}
